import Head from 'next/head';
import {
  AiFillDribbbleCircle,
  AiFillLinkedin,
  AiFillInstagram,
} from "react-icons/ai";
import { useState } from "react";
import {BsFillMoonFill} from 'react-icons/bs';
import image from "../public/Bitmoji.png";
import design from "../public/design.jpg"
import Image from "next/image";


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

return (
  <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portfolio Alex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className=" min-h-screen">
         <nav className="py-10 mb-12 flex justify-between dark:text-white">
           <h1 className=" font-mono  text-xl">BABANKS</h1>
            <ul className="flex items-center">
              <li>
              <BsFillMoonFill onClick={ ()=> setDarkMode (!darkMode)} className="cursor-pointer text-2xl" />
              </li>
              <li>
              <a className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8" href="https://alexisvatrinet.github.io/Alexisvatrinet/">Resume</a>
              </li>
            </ul>
            </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">Alexis Vatrinet</h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">Développeur</h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">Here is my portfolio that I use to put my personal projects on the site </p>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
                <a href="https://www.instagram.com/alexis_vatrinet/"><AiFillInstagram /></a>
              <a href="https://dribbble.com/Alexis-V"><AiFillDribbbleCircle /></a>
              <a href="https://www.linkedin.com/in/alexis-vatrinet/"><AiFillLinkedin  /></a>
              
          </div>
          <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={image} layout="fill" objectFit="cover" />
            </div>
            </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white"> Service i offert</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">Since the beginning of my career as a developer I have developed on several applications, website, graphic model</p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <Image />
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Adobe xd</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Zeplin</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image/>
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Code your dream project
              </h3>
              <p className="py-2">Create the application or site of your dreams? it is possible</p>
              <h4 className="py-4 text-teal-600">Tools I Use</h4>
              <p className="text-gray-800 py-1">Framework JS</p>
              <p className="text-gray-800 py-1">Flutter / Xcode</p>
              <p className="text-gray-800 py-1">NodeJs</p>
              <p className="text-gray-800 py-1">Java</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image /> 
              <h3 className="text-lg font-medium pt-8 pb-2 ">Project</h3>
              <p className="py-2">Mini projects on current technology to you propose</p>
              <h4 className="py-4 text-teal-600">Different type of project</h4>
              <p className="text-gray-800 py-1">Widget</p>
              <p className="text-gray-800 py-1">Api</p>
              <p className="text-gray-800 py-1">Mini Games</p>
              <p className="text-gray-800 py-1">Crawler</p>
            </div>
          </div>
        </section>
       
      </main>


    </div>
  );
  
}
